apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser02-delivery
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/deliveries'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/deliveries'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
